# Generated by Django 5.0.2 on 2024-03-14 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_invitation_sender_alter_team_name_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
