# Generated by Django 5.0.2 on 2024-03-06 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_customuser_email_alter_customuser_full_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
