# Generated by Django 5.0.2 on 2024-03-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_invitation_sender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('sender', 'receiver', 'team')},
        ),
    ]
