# Generated by Django 5.0.2 on 2024-03-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_invitation_unique_together_invitation_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
