# Generated by Django 5.0.2 on 2024-03-18 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_team_unique_together_alter_team_creator_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('sender', 'receiver', 'team', 'role')},
        ),
    ]
