# Generated by Django 5.0.2 on 2024-03-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_invitation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member_count',
            field=models.IntegerField(default=0),
        ),
    ]
