# Generated by Django 5.0.2 on 2024-03-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_team_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Is Complete'),
        ),
    ]
