# Generated by Django 5.0.2 on 2024-04-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_tournamentregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='teams',
        ),
    ]
