# Generated by Django 5.0.2 on 2024-05-07 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_remove_tournament_limit_remove_tournament_teams'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
