# Generated by Django 5.0.2 on 2024-06-15 18:18

import django.contrib.auth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='gameschedule',
            name='vote_updated_by',
            field=models.ManyToManyField(blank=True, related_name='voted_games', to=settings.AUTH_USER_MODEL),
        ),
    ]
